name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # =========================
  # TEST + LINT + TYPESCRIPT
  # =========================
  test:
    name: Test, Lint and TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Run lint
        run: npm run lint

      - name: TypeScript check
        run: npm run typecheck


  # =========================
  # ANDROID AAB BUILD
  # =========================
  android:
    name: Android Release AAB
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Make Gradle wrapper executable
        working-directory: android
        run: chmod +x gradlew

      - name: Build Android Release AAB
        working-directory: android
        run: ./gradlew assembleDebug
        # run: ./gradlew bundleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: QueryDemo-release-aab
          path: android/app/build/outputs/apk/debug/app-debug.apk
          # path: android/app/build/outputs/bundle/release/app-release.aab


# =========================
# iOS CI/CD - HIDDEN FOR NOW
# =========================
#
#  ios:
#    name: iOS Build
#    runs-on: macos-latest
#    needs:
#      - test
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 22
#          cache: npm
#
#      - run: npm ci
#
#      - name: Install CocoaPods
#        working-directory: ios
#        run: pod install
#
#      - name: Build iOS
#        working-directory: ios
#        run: |
#          xcodebuild \
#            -workspace QueryDemo.xcworkspace \
#            -scheme QueryDemo \
#            -configuration Debug \
#            -sdk iphonesimulator \
#            -destination 'generic/platform=iOS Simulator' \
#            CODE_SIGNING_ALLOWED=NO \
#            CODE_SIGNING_REQUIRED=NO \
#            build